# Generated by Django 4.1 on 2022-11-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_irani'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='irani',
            field=models.BooleanField(default=False),
        ),
    ]
